title: 'dmachlanski'

header_pages:
  - index.md
  - research.md
  #- teaching.md
  - posts.md
  #- cv.md

footer: 'follow me on <a href="https://twitter.com/dmachlanski">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
